version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
      POSTGRES_DB: erpdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
  api:
    build: ./fastapi_app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg2://erp:erp@db:5432/erpdb
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: supersecretkey_change_me
      JWT_ALG: HS256
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
  # Optional: Frappe/ERPNext container skeleton for CRUD UI (advanced)
  # Uncomment to experiment locally; full Frappe setup is heavy
  # frappe:
  #   image: frappe/erpnext:v15.31.0
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SITE_NAME=erp.local
  #     - DB_ROOT_USER=postgres
  #     - MYSQL_ROOT_PASSWORD=unsafe
  #   depends_on:
  #     - db
volumes:
  db_data:


  metabase:
    image: metabase/metabase:latest
    restart: unless-stopped
    environment:
      MB_DB_FILE: /metabase.db
    depends_on:
      - db
    ports:
      - "3000:3000"
