name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          flake8 fastapi_app utils tests
          black --check fastapi_app utils tests
      - name: Tests
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=fastapi_app --cov=utils --cov-fail-under=85
